---

- name: Create swap space
  command: "dd if=/dev/zero of=/mnt/{{ swap_directory }} bs=1M count={{ swap_size_in_megabytes }}"
  when: ansible_swaptotal_mb < 1

- name: Make swap
  command: "mkswap {{ swap_directory }}"
  when: ansible_swaptotal_mb < 1

- name: Add to fstab
  action: "lineinfile dest=/etc/fstab regexp={{ swap_directory }} line={{ swap_directory }} none swap sw 0 0 state=present"

- name: ensure permissions on swapdir 
  file: 
    path="{{ swap_directory }}"
    owner=root
    group=root
    state=directory
    mode=0600
  notify:
    - turn swap on

- name: Set swappiness (ubuntu default is 60)
  shell: echo {{swappiness_value}} | sudo tee /proc/sys/vm/swappiness